[package]
name = "dithers"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
image = "0.25.6"
rayon = "1.10.0"

[lib]
name = "dithers"
path = "src/lib.rs"

[[bin]]
name = "dithers"
path = "src/main.rs"
